# Generated by Django 4.2.4 on 2023-09-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_rooms_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messeag',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='base.rooms'),
        ),
    ]
