# Generated by Django 4.2.4 on 2023-09-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
